/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomerServicePolicyRouteImport } from './routes/customer-service-policy'
import { Route as DistributorsRouteImport } from './routes/distributors'
import { Route as TerminalOptionsRouteImport } from './routes/terminal-options'
import { Route as WebAccessibilityStatementRouteImport } from './routes/web-accessibility-statement'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutAgmMediaCenterRouteImport } from './routes/about.agm-media-center'
import { Route as AboutSunXtenderVsFloodedRouteImport } from './routes/about.sun-xtender-vs-flooded'
import { Route as AboutSunXtenderVsGelRouteImport } from './routes/about.sun-xtender-vs-gel'
import { Route as AboutSunXtenderVsOtherAgmRouteImport } from './routes/about.sun-xtender-vs-other-agm'
import { Route as ApplicationsEnergyStorageBackupPowerRouteImport } from './routes/applications.energy-storage-backup-power'
import { Route as ApplicationsGridTiedRouteImport } from './routes/applications.grid-tied'
import { Route as ApplicationsOffGridSystemsRouteImport } from './routes/applications.off-grid-systems'
import { Route as ApplicationsSmartGridSystemsRouteImport } from './routes/applications.smart-grid-systems'
import { Route as ApplicationsSolarStreetLightsRouteImport } from './routes/applications.solar-street-lights'
import { Route as ContactFaqsRouteImport } from './routes/contact_.faqs'
import { Route as ContactSitemapRouteImport } from './routes/contact_.sitemap'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSkuRouteImport } from './routes/products.$sku'
import { Route as ProductsWhySunxtenderBatteriesRouteImport } from './routes/products.why-sunxtender-batteries'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as TechnicalBatteryBanksInstallationsRouteImport } from './routes/technical.battery-banks-installations'
import { Route as TechnicalBatterySizingRouteImport } from './routes/technical.battery-sizing'
import { Route as TechnicalConstructionAndDesignRouteImport } from './routes/technical.construction-and-design'
import { Route as TechnicalElectrolyteContentRouteImport } from './routes/technical.electrolyte-content'
import { Route as TechnicalEuReachArticle33RouteImport } from './routes/technical.eu-reach-article-33'
import { Route as TechnicalIrIssValuesRouteImport } from './routes/technical.ir-iss-values'
import { Route as TechnicalIso9001As9100RouteImport } from './routes/technical.iso-9001-as9100'
import { Route as TechnicalLimitedWarrantyRouteImport } from './routes/technical.limited-warranty'
import { Route as TechnicalSdsRouteImport } from './routes/technical.sds'
import { Route as TechnicalTechnicalDataRouteImport } from './routes/technical.technical-data'
import { Route as TechnicalTechnicalManualRouteImport } from './routes/technical.technical-manual'
import { Route as TechnicalTransportationRouteImport } from './routes/technical.transportation'
import { Route as TechnicalWarrantyClaimFormRouteImport } from './routes/technical.warranty-claim-form'
import { Route as AboutPressReleasesIndexRouteImport } from './routes/about.press-releases.index'
import { Route as AboutPressReleasesCaltransSpecifiesSunXtenderRouteImport } from './routes/about.press-releases.caltrans-specifies-sun-xtender'
import { Route as AboutPressReleasesNewHigherCapacityGroup31BatteriesRouteImport } from './routes/about.press-releases.new-higher-capacity-group-31-batteries'
import { Route as AboutPressReleasesSunXtenderLaunchesNewWebsiteRouteImport } from './routes/about.press-releases.sun-xtender-launches-new-website'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServicePolicyRoute = CustomerServicePolicyRouteImport.update({
  id: '/customer-service-policy',
  path: '/customer-service-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributorsRoute = DistributorsRouteImport.update({
  id: '/distributors',
  path: '/distributors',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalOptionsRoute = TerminalOptionsRouteImport.update({
  id: '/terminal-options',
  path: '/terminal-options',
  getParentRoute: () => rootRouteImport,
} as any)
const WebAccessibilityStatementRoute =
  WebAccessibilityStatementRouteImport.update({
    id: '/web-accessibility-statement',
    path: '/web-accessibility-statement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAgmMediaCenterRoute = AboutAgmMediaCenterRouteImport.update({
  id: '/about/agm-media-center',
  path: '/about/agm-media-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSunXtenderVsFloodedRoute =
  AboutSunXtenderVsFloodedRouteImport.update({
    id: '/about/sun-xtender-vs-flooded',
    path: '/about/sun-xtender-vs-flooded',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutSunXtenderVsGelRoute = AboutSunXtenderVsGelRouteImport.update({
  id: '/about/sun-xtender-vs-gel',
  path: '/about/sun-xtender-vs-gel',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSunXtenderVsOtherAgmRoute =
  AboutSunXtenderVsOtherAgmRouteImport.update({
    id: '/about/sun-xtender-vs-other-agm',
    path: '/about/sun-xtender-vs-other-agm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsEnergyStorageBackupPowerRoute =
  ApplicationsEnergyStorageBackupPowerRouteImport.update({
    id: '/applications/energy-storage-backup-power',
    path: '/applications/energy-storage-backup-power',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsGridTiedRoute = ApplicationsGridTiedRouteImport.update({
  id: '/applications/grid-tied',
  path: '/applications/grid-tied',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsOffGridSystemsRoute =
  ApplicationsOffGridSystemsRouteImport.update({
    id: '/applications/off-grid-systems',
    path: '/applications/off-grid-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsSmartGridSystemsRoute =
  ApplicationsSmartGridSystemsRouteImport.update({
    id: '/applications/smart-grid-systems',
    path: '/applications/smart-grid-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsSolarStreetLightsRoute =
  ApplicationsSolarStreetLightsRouteImport.update({
    id: '/applications/solar-street-lights',
    path: '/applications/solar-street-lights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactFaqsRoute = ContactFaqsRouteImport.update({
  id: '/contact_/faqs',
  path: '/contact/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactSitemapRoute = ContactSitemapRouteImport.update({
  id: '/contact_/sitemap',
  path: '/contact/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSkuRoute = ProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWhySunxtenderBatteriesRoute =
  ProductsWhySunxtenderBatteriesRouteImport.update({
    id: '/products/why-sunxtender-batteries',
    path: '/products/why-sunxtender-batteries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalBatteryBanksInstallationsRoute =
  TechnicalBatteryBanksInstallationsRouteImport.update({
    id: '/technical/battery-banks-installations',
    path: '/technical/battery-banks-installations',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnicalBatterySizingRoute = TechnicalBatterySizingRouteImport.update({
  id: '/technical/battery-sizing',
  path: '/technical/battery-sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalConstructionAndDesignRoute =
  TechnicalConstructionAndDesignRouteImport.update({
    id: '/technical/construction-and-design',
    path: '/technical/construction-and-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnicalElectrolyteContentRoute =
  TechnicalElectrolyteContentRouteImport.update({
    id: '/technical/electrolyte-content',
    path: '/technical/electrolyte-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnicalEuReachArticle33Route =
  TechnicalEuReachArticle33RouteImport.update({
    id: '/technical/eu-reach-article-33',
    path: '/technical/eu-reach-article-33',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnicalIrIssValuesRoute = TechnicalIrIssValuesRouteImport.update({
  id: '/technical/ir-iss-values',
  path: '/technical/ir-iss-values',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalIso9001As9100Route = TechnicalIso9001As9100RouteImport.update({
  id: '/technical/iso-9001-as9100',
  path: '/technical/iso-9001-as9100',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalLimitedWarrantyRoute =
  TechnicalLimitedWarrantyRouteImport.update({
    id: '/technical/limited-warranty',
    path: '/technical/limited-warranty',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnicalSdsRoute = TechnicalSdsRouteImport.update({
  id: '/technical/sds',
  path: '/technical/sds',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalTechnicalDataRoute = TechnicalTechnicalDataRouteImport.update({
  id: '/technical/technical-data',
  path: '/technical/technical-data',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalTechnicalManualRoute =
  TechnicalTechnicalManualRouteImport.update({
    id: '/technical/technical-manual',
    path: '/technical/technical-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const TechnicalTransportationRoute = TechnicalTransportationRouteImport.update({
  id: '/technical/transportation',
  path: '/technical/transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalWarrantyClaimFormRoute =
  TechnicalWarrantyClaimFormRouteImport.update({
    id: '/technical/warranty-claim-form',
    path: '/technical/warranty-claim-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutPressReleasesIndexRoute = AboutPressReleasesIndexRouteImport.update({
  id: '/about/press-releases/',
  path: '/about/press-releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPressReleasesCaltransSpecifiesSunXtenderRoute =
  AboutPressReleasesCaltransSpecifiesSunXtenderRouteImport.update({
    id: '/about/press-releases/caltrans-specifies-sun-xtender',
    path: '/about/press-releases/caltrans-specifies-sun-xtender',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute =
  AboutPressReleasesNewHigherCapacityGroup31BatteriesRouteImport.update({
    id: '/about/press-releases/new-higher-capacity-group-31-batteries',
    path: '/about/press-releases/new-higher-capacity-group-31-batteries',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute =
  AboutPressReleasesSunXtenderLaunchesNewWebsiteRouteImport.update({
    id: '/about/press-releases/sun-xtender-launches-new-website',
    path: '/about/press-releases/sun-xtender-launches-new-website',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/customer-service-policy': typeof CustomerServicePolicyRoute
  '/distributors': typeof DistributorsRoute
  '/terminal-options': typeof TerminalOptionsRoute
  '/web-accessibility-statement': typeof WebAccessibilityStatementRoute
  '/about/agm-media-center': typeof AboutAgmMediaCenterRoute
  '/about/sun-xtender-vs-flooded': typeof AboutSunXtenderVsFloodedRoute
  '/about/sun-xtender-vs-gel': typeof AboutSunXtenderVsGelRoute
  '/about/sun-xtender-vs-other-agm': typeof AboutSunXtenderVsOtherAgmRoute
  '/applications/energy-storage-backup-power': typeof ApplicationsEnergyStorageBackupPowerRoute
  '/applications/grid-tied': typeof ApplicationsGridTiedRoute
  '/applications/off-grid-systems': typeof ApplicationsOffGridSystemsRoute
  '/applications/smart-grid-systems': typeof ApplicationsSmartGridSystemsRoute
  '/applications/solar-street-lights': typeof ApplicationsSolarStreetLightsRoute
  '/contact/faqs': typeof ContactFaqsRoute
  '/contact/sitemap': typeof ContactSitemapRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/products/why-sunxtender-batteries': typeof ProductsWhySunxtenderBatteriesRoute
  '/technical/battery-banks-installations': typeof TechnicalBatteryBanksInstallationsRoute
  '/technical/battery-sizing': typeof TechnicalBatterySizingRoute
  '/technical/construction-and-design': typeof TechnicalConstructionAndDesignRoute
  '/technical/electrolyte-content': typeof TechnicalElectrolyteContentRoute
  '/technical/eu-reach-article-33': typeof TechnicalEuReachArticle33Route
  '/technical/ir-iss-values': typeof TechnicalIrIssValuesRoute
  '/technical/iso-9001-as9100': typeof TechnicalIso9001As9100Route
  '/technical/limited-warranty': typeof TechnicalLimitedWarrantyRoute
  '/technical/sds': typeof TechnicalSdsRoute
  '/technical/technical-data': typeof TechnicalTechnicalDataRoute
  '/technical/technical-manual': typeof TechnicalTechnicalManualRoute
  '/technical/transportation': typeof TechnicalTransportationRoute
  '/technical/warranty-claim-form': typeof TechnicalWarrantyClaimFormRoute
  '/about/': typeof AboutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/about/press-releases/caltrans-specifies-sun-xtender': typeof AboutPressReleasesCaltransSpecifiesSunXtenderRoute
  '/about/press-releases/new-higher-capacity-group-31-batteries': typeof AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute
  '/about/press-releases/sun-xtender-launches-new-website': typeof AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute
  '/about/press-releases/': typeof AboutPressReleasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/customer-service-policy': typeof CustomerServicePolicyRoute
  '/distributors': typeof DistributorsRoute
  '/terminal-options': typeof TerminalOptionsRoute
  '/web-accessibility-statement': typeof WebAccessibilityStatementRoute
  '/about/agm-media-center': typeof AboutAgmMediaCenterRoute
  '/about/sun-xtender-vs-flooded': typeof AboutSunXtenderVsFloodedRoute
  '/about/sun-xtender-vs-gel': typeof AboutSunXtenderVsGelRoute
  '/about/sun-xtender-vs-other-agm': typeof AboutSunXtenderVsOtherAgmRoute
  '/applications/energy-storage-backup-power': typeof ApplicationsEnergyStorageBackupPowerRoute
  '/applications/grid-tied': typeof ApplicationsGridTiedRoute
  '/applications/off-grid-systems': typeof ApplicationsOffGridSystemsRoute
  '/applications/smart-grid-systems': typeof ApplicationsSmartGridSystemsRoute
  '/applications/solar-street-lights': typeof ApplicationsSolarStreetLightsRoute
  '/contact/faqs': typeof ContactFaqsRoute
  '/contact/sitemap': typeof ContactSitemapRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/products/why-sunxtender-batteries': typeof ProductsWhySunxtenderBatteriesRoute
  '/technical/battery-banks-installations': typeof TechnicalBatteryBanksInstallationsRoute
  '/technical/battery-sizing': typeof TechnicalBatterySizingRoute
  '/technical/construction-and-design': typeof TechnicalConstructionAndDesignRoute
  '/technical/electrolyte-content': typeof TechnicalElectrolyteContentRoute
  '/technical/eu-reach-article-33': typeof TechnicalEuReachArticle33Route
  '/technical/ir-iss-values': typeof TechnicalIrIssValuesRoute
  '/technical/iso-9001-as9100': typeof TechnicalIso9001As9100Route
  '/technical/limited-warranty': typeof TechnicalLimitedWarrantyRoute
  '/technical/sds': typeof TechnicalSdsRoute
  '/technical/technical-data': typeof TechnicalTechnicalDataRoute
  '/technical/technical-manual': typeof TechnicalTechnicalManualRoute
  '/technical/transportation': typeof TechnicalTransportationRoute
  '/technical/warranty-claim-form': typeof TechnicalWarrantyClaimFormRoute
  '/about': typeof AboutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/about/press-releases/caltrans-specifies-sun-xtender': typeof AboutPressReleasesCaltransSpecifiesSunXtenderRoute
  '/about/press-releases/new-higher-capacity-group-31-batteries': typeof AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute
  '/about/press-releases/sun-xtender-launches-new-website': typeof AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute
  '/about/press-releases': typeof AboutPressReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/customer-service-policy': typeof CustomerServicePolicyRoute
  '/distributors': typeof DistributorsRoute
  '/terminal-options': typeof TerminalOptionsRoute
  '/web-accessibility-statement': typeof WebAccessibilityStatementRoute
  '/about/agm-media-center': typeof AboutAgmMediaCenterRoute
  '/about/sun-xtender-vs-flooded': typeof AboutSunXtenderVsFloodedRoute
  '/about/sun-xtender-vs-gel': typeof AboutSunXtenderVsGelRoute
  '/about/sun-xtender-vs-other-agm': typeof AboutSunXtenderVsOtherAgmRoute
  '/applications/energy-storage-backup-power': typeof ApplicationsEnergyStorageBackupPowerRoute
  '/applications/grid-tied': typeof ApplicationsGridTiedRoute
  '/applications/off-grid-systems': typeof ApplicationsOffGridSystemsRoute
  '/applications/smart-grid-systems': typeof ApplicationsSmartGridSystemsRoute
  '/applications/solar-street-lights': typeof ApplicationsSolarStreetLightsRoute
  '/contact_/faqs': typeof ContactFaqsRoute
  '/contact_/sitemap': typeof ContactSitemapRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/products/why-sunxtender-batteries': typeof ProductsWhySunxtenderBatteriesRoute
  '/technical/battery-banks-installations': typeof TechnicalBatteryBanksInstallationsRoute
  '/technical/battery-sizing': typeof TechnicalBatterySizingRoute
  '/technical/construction-and-design': typeof TechnicalConstructionAndDesignRoute
  '/technical/electrolyte-content': typeof TechnicalElectrolyteContentRoute
  '/technical/eu-reach-article-33': typeof TechnicalEuReachArticle33Route
  '/technical/ir-iss-values': typeof TechnicalIrIssValuesRoute
  '/technical/iso-9001-as9100': typeof TechnicalIso9001As9100Route
  '/technical/limited-warranty': typeof TechnicalLimitedWarrantyRoute
  '/technical/sds': typeof TechnicalSdsRoute
  '/technical/technical-data': typeof TechnicalTechnicalDataRoute
  '/technical/technical-manual': typeof TechnicalTechnicalManualRoute
  '/technical/transportation': typeof TechnicalTransportationRoute
  '/technical/warranty-claim-form': typeof TechnicalWarrantyClaimFormRoute
  '/about/': typeof AboutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/about/press-releases/caltrans-specifies-sun-xtender': typeof AboutPressReleasesCaltransSpecifiesSunXtenderRoute
  '/about/press-releases/new-higher-capacity-group-31-batteries': typeof AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute
  '/about/press-releases/sun-xtender-launches-new-website': typeof AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute
  '/about/press-releases/': typeof AboutPressReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/customer-service-policy'
    | '/distributors'
    | '/terminal-options'
    | '/web-accessibility-statement'
    | '/about/agm-media-center'
    | '/about/sun-xtender-vs-flooded'
    | '/about/sun-xtender-vs-gel'
    | '/about/sun-xtender-vs-other-agm'
    | '/applications/energy-storage-backup-power'
    | '/applications/grid-tied'
    | '/applications/off-grid-systems'
    | '/applications/smart-grid-systems'
    | '/applications/solar-street-lights'
    | '/contact/faqs'
    | '/contact/sitemap'
    | '/products/$sku'
    | '/products/why-sunxtender-batteries'
    | '/technical/battery-banks-installations'
    | '/technical/battery-sizing'
    | '/technical/construction-and-design'
    | '/technical/electrolyte-content'
    | '/technical/eu-reach-article-33'
    | '/technical/ir-iss-values'
    | '/technical/iso-9001-as9100'
    | '/technical/limited-warranty'
    | '/technical/sds'
    | '/technical/technical-data'
    | '/technical/technical-manual'
    | '/technical/transportation'
    | '/technical/warranty-claim-form'
    | '/about/'
    | '/products/'
    | '/resources/'
    | '/about/press-releases/caltrans-specifies-sun-xtender'
    | '/about/press-releases/new-higher-capacity-group-31-batteries'
    | '/about/press-releases/sun-xtender-launches-new-website'
    | '/about/press-releases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/customer-service-policy'
    | '/distributors'
    | '/terminal-options'
    | '/web-accessibility-statement'
    | '/about/agm-media-center'
    | '/about/sun-xtender-vs-flooded'
    | '/about/sun-xtender-vs-gel'
    | '/about/sun-xtender-vs-other-agm'
    | '/applications/energy-storage-backup-power'
    | '/applications/grid-tied'
    | '/applications/off-grid-systems'
    | '/applications/smart-grid-systems'
    | '/applications/solar-street-lights'
    | '/contact/faqs'
    | '/contact/sitemap'
    | '/products/$sku'
    | '/products/why-sunxtender-batteries'
    | '/technical/battery-banks-installations'
    | '/technical/battery-sizing'
    | '/technical/construction-and-design'
    | '/technical/electrolyte-content'
    | '/technical/eu-reach-article-33'
    | '/technical/ir-iss-values'
    | '/technical/iso-9001-as9100'
    | '/technical/limited-warranty'
    | '/technical/sds'
    | '/technical/technical-data'
    | '/technical/technical-manual'
    | '/technical/transportation'
    | '/technical/warranty-claim-form'
    | '/about'
    | '/products'
    | '/resources'
    | '/about/press-releases/caltrans-specifies-sun-xtender'
    | '/about/press-releases/new-higher-capacity-group-31-batteries'
    | '/about/press-releases/sun-xtender-launches-new-website'
    | '/about/press-releases'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/customer-service-policy'
    | '/distributors'
    | '/terminal-options'
    | '/web-accessibility-statement'
    | '/about/agm-media-center'
    | '/about/sun-xtender-vs-flooded'
    | '/about/sun-xtender-vs-gel'
    | '/about/sun-xtender-vs-other-agm'
    | '/applications/energy-storage-backup-power'
    | '/applications/grid-tied'
    | '/applications/off-grid-systems'
    | '/applications/smart-grid-systems'
    | '/applications/solar-street-lights'
    | '/contact_/faqs'
    | '/contact_/sitemap'
    | '/products/$sku'
    | '/products/why-sunxtender-batteries'
    | '/technical/battery-banks-installations'
    | '/technical/battery-sizing'
    | '/technical/construction-and-design'
    | '/technical/electrolyte-content'
    | '/technical/eu-reach-article-33'
    | '/technical/ir-iss-values'
    | '/technical/iso-9001-as9100'
    | '/technical/limited-warranty'
    | '/technical/sds'
    | '/technical/technical-data'
    | '/technical/technical-manual'
    | '/technical/transportation'
    | '/technical/warranty-claim-form'
    | '/about/'
    | '/products/'
    | '/resources/'
    | '/about/press-releases/caltrans-specifies-sun-xtender'
    | '/about/press-releases/new-higher-capacity-group-31-batteries'
    | '/about/press-releases/sun-xtender-launches-new-website'
    | '/about/press-releases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CustomerServicePolicyRoute: typeof CustomerServicePolicyRoute
  DistributorsRoute: typeof DistributorsRoute
  TerminalOptionsRoute: typeof TerminalOptionsRoute
  WebAccessibilityStatementRoute: typeof WebAccessibilityStatementRoute
  AboutAgmMediaCenterRoute: typeof AboutAgmMediaCenterRoute
  AboutSunXtenderVsFloodedRoute: typeof AboutSunXtenderVsFloodedRoute
  AboutSunXtenderVsGelRoute: typeof AboutSunXtenderVsGelRoute
  AboutSunXtenderVsOtherAgmRoute: typeof AboutSunXtenderVsOtherAgmRoute
  ApplicationsEnergyStorageBackupPowerRoute: typeof ApplicationsEnergyStorageBackupPowerRoute
  ApplicationsGridTiedRoute: typeof ApplicationsGridTiedRoute
  ApplicationsOffGridSystemsRoute: typeof ApplicationsOffGridSystemsRoute
  ApplicationsSmartGridSystemsRoute: typeof ApplicationsSmartGridSystemsRoute
  ApplicationsSolarStreetLightsRoute: typeof ApplicationsSolarStreetLightsRoute
  ContactFaqsRoute: typeof ContactFaqsRoute
  ContactSitemapRoute: typeof ContactSitemapRoute
  ProductsSkuRoute: typeof ProductsSkuRoute
  ProductsWhySunxtenderBatteriesRoute: typeof ProductsWhySunxtenderBatteriesRoute
  TechnicalBatteryBanksInstallationsRoute: typeof TechnicalBatteryBanksInstallationsRoute
  TechnicalBatterySizingRoute: typeof TechnicalBatterySizingRoute
  TechnicalConstructionAndDesignRoute: typeof TechnicalConstructionAndDesignRoute
  TechnicalElectrolyteContentRoute: typeof TechnicalElectrolyteContentRoute
  TechnicalEuReachArticle33Route: typeof TechnicalEuReachArticle33Route
  TechnicalIrIssValuesRoute: typeof TechnicalIrIssValuesRoute
  TechnicalIso9001As9100Route: typeof TechnicalIso9001As9100Route
  TechnicalLimitedWarrantyRoute: typeof TechnicalLimitedWarrantyRoute
  TechnicalSdsRoute: typeof TechnicalSdsRoute
  TechnicalTechnicalDataRoute: typeof TechnicalTechnicalDataRoute
  TechnicalTechnicalManualRoute: typeof TechnicalTechnicalManualRoute
  TechnicalTransportationRoute: typeof TechnicalTransportationRoute
  TechnicalWarrantyClaimFormRoute: typeof TechnicalWarrantyClaimFormRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  AboutPressReleasesCaltransSpecifiesSunXtenderRoute: typeof AboutPressReleasesCaltransSpecifiesSunXtenderRoute
  AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute: typeof AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute
  AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute: typeof AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute
  AboutPressReleasesIndexRoute: typeof AboutPressReleasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service-policy': {
      id: '/customer-service-policy'
      path: '/customer-service-policy'
      fullPath: '/customer-service-policy'
      preLoaderRoute: typeof CustomerServicePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distributors': {
      id: '/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof DistributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal-options': {
      id: '/terminal-options'
      path: '/terminal-options'
      fullPath: '/terminal-options'
      preLoaderRoute: typeof TerminalOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-accessibility-statement': {
      id: '/web-accessibility-statement'
      path: '/web-accessibility-statement'
      fullPath: '/web-accessibility-statement'
      preLoaderRoute: typeof WebAccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/agm-media-center': {
      id: '/about/agm-media-center'
      path: '/about/agm-media-center'
      fullPath: '/about/agm-media-center'
      preLoaderRoute: typeof AboutAgmMediaCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sun-xtender-vs-flooded': {
      id: '/about/sun-xtender-vs-flooded'
      path: '/about/sun-xtender-vs-flooded'
      fullPath: '/about/sun-xtender-vs-flooded'
      preLoaderRoute: typeof AboutSunXtenderVsFloodedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sun-xtender-vs-gel': {
      id: '/about/sun-xtender-vs-gel'
      path: '/about/sun-xtender-vs-gel'
      fullPath: '/about/sun-xtender-vs-gel'
      preLoaderRoute: typeof AboutSunXtenderVsGelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/sun-xtender-vs-other-agm': {
      id: '/about/sun-xtender-vs-other-agm'
      path: '/about/sun-xtender-vs-other-agm'
      fullPath: '/about/sun-xtender-vs-other-agm'
      preLoaderRoute: typeof AboutSunXtenderVsOtherAgmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/energy-storage-backup-power': {
      id: '/applications/energy-storage-backup-power'
      path: '/applications/energy-storage-backup-power'
      fullPath: '/applications/energy-storage-backup-power'
      preLoaderRoute: typeof ApplicationsEnergyStorageBackupPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/grid-tied': {
      id: '/applications/grid-tied'
      path: '/applications/grid-tied'
      fullPath: '/applications/grid-tied'
      preLoaderRoute: typeof ApplicationsGridTiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/off-grid-systems': {
      id: '/applications/off-grid-systems'
      path: '/applications/off-grid-systems'
      fullPath: '/applications/off-grid-systems'
      preLoaderRoute: typeof ApplicationsOffGridSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/smart-grid-systems': {
      id: '/applications/smart-grid-systems'
      path: '/applications/smart-grid-systems'
      fullPath: '/applications/smart-grid-systems'
      preLoaderRoute: typeof ApplicationsSmartGridSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/solar-street-lights': {
      id: '/applications/solar-street-lights'
      path: '/applications/solar-street-lights'
      fullPath: '/applications/solar-street-lights'
      preLoaderRoute: typeof ApplicationsSolarStreetLightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact_/faqs': {
      id: '/contact_/faqs'
      path: '/contact/faqs'
      fullPath: '/contact/faqs'
      preLoaderRoute: typeof ContactFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact_/sitemap': {
      id: '/contact_/sitemap'
      path: '/contact/sitemap'
      fullPath: '/contact/sitemap'
      preLoaderRoute: typeof ContactSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$sku': {
      id: '/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof ProductsSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/why-sunxtender-batteries': {
      id: '/products/why-sunxtender-batteries'
      path: '/products/why-sunxtender-batteries'
      fullPath: '/products/why-sunxtender-batteries'
      preLoaderRoute: typeof ProductsWhySunxtenderBatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/battery-banks-installations': {
      id: '/technical/battery-banks-installations'
      path: '/technical/battery-banks-installations'
      fullPath: '/technical/battery-banks-installations'
      preLoaderRoute: typeof TechnicalBatteryBanksInstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/battery-sizing': {
      id: '/technical/battery-sizing'
      path: '/technical/battery-sizing'
      fullPath: '/technical/battery-sizing'
      preLoaderRoute: typeof TechnicalBatterySizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/construction-and-design': {
      id: '/technical/construction-and-design'
      path: '/technical/construction-and-design'
      fullPath: '/technical/construction-and-design'
      preLoaderRoute: typeof TechnicalConstructionAndDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/electrolyte-content': {
      id: '/technical/electrolyte-content'
      path: '/technical/electrolyte-content'
      fullPath: '/technical/electrolyte-content'
      preLoaderRoute: typeof TechnicalElectrolyteContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/eu-reach-article-33': {
      id: '/technical/eu-reach-article-33'
      path: '/technical/eu-reach-article-33'
      fullPath: '/technical/eu-reach-article-33'
      preLoaderRoute: typeof TechnicalEuReachArticle33RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/ir-iss-values': {
      id: '/technical/ir-iss-values'
      path: '/technical/ir-iss-values'
      fullPath: '/technical/ir-iss-values'
      preLoaderRoute: typeof TechnicalIrIssValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/iso-9001-as9100': {
      id: '/technical/iso-9001-as9100'
      path: '/technical/iso-9001-as9100'
      fullPath: '/technical/iso-9001-as9100'
      preLoaderRoute: typeof TechnicalIso9001As9100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/limited-warranty': {
      id: '/technical/limited-warranty'
      path: '/technical/limited-warranty'
      fullPath: '/technical/limited-warranty'
      preLoaderRoute: typeof TechnicalLimitedWarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/sds': {
      id: '/technical/sds'
      path: '/technical/sds'
      fullPath: '/technical/sds'
      preLoaderRoute: typeof TechnicalSdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/technical-data': {
      id: '/technical/technical-data'
      path: '/technical/technical-data'
      fullPath: '/technical/technical-data'
      preLoaderRoute: typeof TechnicalTechnicalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/technical-manual': {
      id: '/technical/technical-manual'
      path: '/technical/technical-manual'
      fullPath: '/technical/technical-manual'
      preLoaderRoute: typeof TechnicalTechnicalManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/transportation': {
      id: '/technical/transportation'
      path: '/technical/transportation'
      fullPath: '/technical/transportation'
      preLoaderRoute: typeof TechnicalTransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical/warranty-claim-form': {
      id: '/technical/warranty-claim-form'
      path: '/technical/warranty-claim-form'
      fullPath: '/technical/warranty-claim-form'
      preLoaderRoute: typeof TechnicalWarrantyClaimFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/press-releases/': {
      id: '/about/press-releases/'
      path: '/about/press-releases'
      fullPath: '/about/press-releases/'
      preLoaderRoute: typeof AboutPressReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/press-releases/caltrans-specifies-sun-xtender': {
      id: '/about/press-releases/caltrans-specifies-sun-xtender'
      path: '/about/press-releases/caltrans-specifies-sun-xtender'
      fullPath: '/about/press-releases/caltrans-specifies-sun-xtender'
      preLoaderRoute: typeof AboutPressReleasesCaltransSpecifiesSunXtenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/press-releases/new-higher-capacity-group-31-batteries': {
      id: '/about/press-releases/new-higher-capacity-group-31-batteries'
      path: '/about/press-releases/new-higher-capacity-group-31-batteries'
      fullPath: '/about/press-releases/new-higher-capacity-group-31-batteries'
      preLoaderRoute: typeof AboutPressReleasesNewHigherCapacityGroup31BatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/press-releases/sun-xtender-launches-new-website': {
      id: '/about/press-releases/sun-xtender-launches-new-website'
      path: '/about/press-releases/sun-xtender-launches-new-website'
      fullPath: '/about/press-releases/sun-xtender-launches-new-website'
      preLoaderRoute: typeof AboutPressReleasesSunXtenderLaunchesNewWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CustomerServicePolicyRoute: CustomerServicePolicyRoute,
  DistributorsRoute: DistributorsRoute,
  TerminalOptionsRoute: TerminalOptionsRoute,
  WebAccessibilityStatementRoute: WebAccessibilityStatementRoute,
  AboutAgmMediaCenterRoute: AboutAgmMediaCenterRoute,
  AboutSunXtenderVsFloodedRoute: AboutSunXtenderVsFloodedRoute,
  AboutSunXtenderVsGelRoute: AboutSunXtenderVsGelRoute,
  AboutSunXtenderVsOtherAgmRoute: AboutSunXtenderVsOtherAgmRoute,
  ApplicationsEnergyStorageBackupPowerRoute:
    ApplicationsEnergyStorageBackupPowerRoute,
  ApplicationsGridTiedRoute: ApplicationsGridTiedRoute,
  ApplicationsOffGridSystemsRoute: ApplicationsOffGridSystemsRoute,
  ApplicationsSmartGridSystemsRoute: ApplicationsSmartGridSystemsRoute,
  ApplicationsSolarStreetLightsRoute: ApplicationsSolarStreetLightsRoute,
  ContactFaqsRoute: ContactFaqsRoute,
  ContactSitemapRoute: ContactSitemapRoute,
  ProductsSkuRoute: ProductsSkuRoute,
  ProductsWhySunxtenderBatteriesRoute: ProductsWhySunxtenderBatteriesRoute,
  TechnicalBatteryBanksInstallationsRoute:
    TechnicalBatteryBanksInstallationsRoute,
  TechnicalBatterySizingRoute: TechnicalBatterySizingRoute,
  TechnicalConstructionAndDesignRoute: TechnicalConstructionAndDesignRoute,
  TechnicalElectrolyteContentRoute: TechnicalElectrolyteContentRoute,
  TechnicalEuReachArticle33Route: TechnicalEuReachArticle33Route,
  TechnicalIrIssValuesRoute: TechnicalIrIssValuesRoute,
  TechnicalIso9001As9100Route: TechnicalIso9001As9100Route,
  TechnicalLimitedWarrantyRoute: TechnicalLimitedWarrantyRoute,
  TechnicalSdsRoute: TechnicalSdsRoute,
  TechnicalTechnicalDataRoute: TechnicalTechnicalDataRoute,
  TechnicalTechnicalManualRoute: TechnicalTechnicalManualRoute,
  TechnicalTransportationRoute: TechnicalTransportationRoute,
  TechnicalWarrantyClaimFormRoute: TechnicalWarrantyClaimFormRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  AboutPressReleasesCaltransSpecifiesSunXtenderRoute:
    AboutPressReleasesCaltransSpecifiesSunXtenderRoute,
  AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute:
    AboutPressReleasesNewHigherCapacityGroup31BatteriesRoute,
  AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute:
    AboutPressReleasesSunXtenderLaunchesNewWebsiteRoute,
  AboutPressReleasesIndexRoute: AboutPressReleasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
